### ISSUE TITLE
bower version out of date

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerLabs/polymer-externs#26]
Bower has up to version 1.0.9 which points at 7bc8688bbd33aa5f073c50175f4e5a3ca668f2df, which doesn't have the arrayDelete fix #24 by @jklein24.

How do we pull down the latest via bower?

**Comment by jklein24** [comment]
@rictic, can you push a new release once https://github.com/PolymerLabs/polymer-externs/pull/25 lands?

**Comment by rictic** [comment]
Will do

**Comment by rictic** [comment]
Added version 1.0.10
